services:
  nginx_server:
    image: nginx:stable
    ports: 
      - 8000:80
    volumes:
      - ./nginx_server/confs:/etc/nginx/conf.d
      - ./nginx_server/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - db_server
      - otree_server
  otree_server:
    build: ./otree_server/
    command: sh -c "sleep 10; otree prodserver1of2 0.0.0.0:8000 & sleep 10; otree prodserver2of2"
    env_file: ./envs/otree.env
    volumes:
      - ./otree_server:/otree
    depends_on:
      - db_server
  db_server:
    image: postgres:14
    env_file: ./envs/postgres.env
  drive_server:
    image: filebrowser/filebrowser
    volumes:
      - ./drive_server/filebrowser.json:/.filebrowser.json
      - ./drive_server/database.db:/database.db
      - ./otree_server/participants_data:/otree